### ISSUE TITLE
Simple tool to produce binary recommendations from complex attack outputs

### ISSUE THREAD

**Issue by jim-smith** [AI-SDC/AI-SDC#110]
For now this just needs to parse the json files produced by different attacks and effectively saying
accept
or 
reject because xxx

xxx could be:
|---|--|
| MIA_AUC >0.75 |   works for LIRA / Worst-Case attacks|
| ??? |  for continuous attributes in attribute inference |
| ??? | for categorical attributes in attribute inference|
| reasons from safe models | for 'researcher error' attacks from safemodels|

@rpreen to suggest values for attribute inference

For safemodels, from line 757 in safemodel.py you can see it what it puts into the json file

**Comment by simonrnss** [comment]
Bit more details on @yolaj-nhs and my thinking here...
We will mock up a couple of classes (because any method like this will need parameters that have to be set somehow) that produce various simple outputs from the json.
Initially propose the following (which should be ready before the next WP meeting on Weds 26/04:
1. Mapping of output to a 1-5 risk scale (can be binarised at, say, 3 if we want) [yola]
2. Statistical summary of output in terms of number of repetitions in which the AUC / FDIF had significant p-values (with option for multiple testing). [simon]
3. Plot of log-log ROC curve as an example of graphical output [simon]

@yolaj-nhs has agreed to attach an example json to this thread to help dev.

Something else to think about -- it might be interesting to be able to chain these things together. I.e. I can see that there might be a use for point 2 above to ultimately feed into point 1. This could be easy enough I think...[opens up old software engineering design patterns textbook]

An additional task is making sure we can create realistic enough json output programmatically to enable unit tests to be developed for this. Maybe just need to commit a couple of .json files to somewhere in the repo and load them for the tests....

**Comment by jim-smith** [comment]
Sounds good.
If you look in the example notebooks there. are examples for decision tree/random forest/svc and keras models where the safewrapper code catches the user doing something unsafe or tampering with the model, and the code then reports that o the (rather unhelpfully named) checkpoint.json.  
example attached that arises from running the example-notebook-SVC.ipynb
(with the file extension .txt added so that GitHub would accept it)
[j4-smith_checkfile.json.txt](https://github.com/AI-SDC/AI-SDC/files/11331758/j4-smith_checkfile.json.txt)

**Comment by jim-smith** [comment]
@simonrnss @yolaj-nhs is this completed by another PR, or are we leaving the in place until we have integrated the outputs from safemodels and attribute inference?

**Comment by yolaj-nhs** [comment]
@jim-smith The PR is still in place because we haven't decided specifics with regards to how the final score should be calculated, or what metrics will be included. There is a function that produces a report and a score, but how the score is calculated is yet to be decided.
