### ISSUE TITLE
examples/safemodel_attack_integration_bothcalls.py has to be run inside a 'if __name__ == '__main__'' block

### ISSUE THREAD

**Issue by yolaj-nhs** [AI-SDC/AI-SDC#192]
The safemodel_attack_integration_bothcalls.py causes a Runtime error and the code to completely crash if the `if __name__ == "__main__":` block is removed.

Is this a bug or a feature?

Not a problem if it's expected - I just came across it when creating examples for user stories

**Comment by jim-smith** [comment]
@yolaj-nhs what branch is that?

I changed the if statement so the code inside always ran
if True:#__name__ == "__main__":

and it ran fine in the development branch

**Comment by rpreen** [comment]
If I remember correctly this was something to do with multiprocessing on Windows... basically it will run fine without checking for main on Linux and Unix but wont work on Windows because of the way the sub processes are spawned. Possibly the check for main should get put inside the attribute inference attack instead so it's not necessary in the higher level script...

**Comment by rpreen** [comment]
Looking at this more closely and I'm not sure it can be just put into the attribute attack...

**Comment by rpreen** [comment]
It's just good form anyway to have that main check in the script that you are executing as a main method.

**Comment by rpreen** [comment]
Yeah, I think it's just how it is; it caught me off guard too the first time I ran it on Windows and it crashed and I had to add the main check, but really the check should be in all of the examples although it doesn't seem to matter for the MIAs...
