### ISSUE TITLE
A simple attack on probabilities

### ISSUE THREAD

**Issue by simonrnss** [AI-SDC/AI-SDC#202]
- Most of our example problems are binary classification.
- We assume that a successful attack will happen if the predictive probs of training examples are higher than the validation examples.
- We take the probs, and fit another model on these.

But...

We're training a classifier on data with two features, one of which is one minus the other. We could ditch the attack model altogether...i.e. if we just take the max target model probability for each example, and a label of 1 / 0 (training / validation) then we can directly compute the metrics.

e.g. 

```python
from aisdc import metrics

# train_preds and test_preds are proba preds from the target model
attack_X = np.vstack((train_preds, test_preds))
n_train = len(train_preds)
n_test = len(test_preds)
attack_y = np.hstack((np.ones(n_train), np.zeros(n_test)))
# Sort so that the highest probability for each row is in the second column
# (this is just so the metric calculations are the right way around)
attack_X = np.sort(attack_X, axis=1)

# Use our existing code to compute the metrics
p_only_metrics = metrics.get_metrics(attack_X, attack_y)
```

Some of the metrics are eaiser to interpret from this than when we look at them from the output of the attack model. I.e. 
AUC is equivalent to saying:
> What is the probability that a randomly chosen training point will have a higher max predictive probability than a randomly chosen non-training point?

FDIF is equivalent to saying:
> What is the difference in the proportion of training points in the top 10% of confidences to the bottom 10%

etc

Feels like a very clean and useful metric, and I suspect is basically equivalent to fitting an attack model that can only fit monotonic probability surfaces (e.g. something linear). A RF could fit something more complex.

At this stage, just looking for comment here - is this something we should try and implement?

**Comment by jim-smith** [comment]
@simonrnss like this a lot.

The way that you frame AUC makes it even more obvious to me why I don't think it is a particularly relevant metric in the context of SDC :)

**All** Do we want a separate branch to put notebooks/experiments in? or does that belong in the SACO-ML project rather than AISDC??
 
The attached image displays the  Cumulative Distribution functions for  class probabilities for a disclosive Random Forest trained on a 4-class problem from the nursery data. Forget who provided the params - it is a 50:50 train/test split.

As you can see, for class 1, the distributions are actually pretty similar - there are some differences around the borders where test has probabilities that train does not, but both have big gaps in the middle where no instances exist with 'intermediate' probabilities.    That is not true for the other 3 classes.

<img width="1052" alt="image" src="https://github.com/AI-SDC/AI-SDC/assets/11739683/daed9dc8-4ba2-4329-a792-29b637289203">

Kolgorov-Smirnov tests comparing the CDFs for each class show the Null Hypothesis (both sets sampled from same underlying distribution) can be discounted for all 4 classes.
So we could interpret that as saying 
>there is reasonable grounds to believe that the model has the capacity to leak data.

When I get a chance I will put the code into a loop producing successively less disclose models to see if the KS difference goes away.

Incidentally, the k-anonymity was 1 for every record in  the training data  !

**Comment by jim-smith** [comment]
@simonrnss @rpreen @jamesliley @shahzadmumtaz22 @yolaj-nhs @drchriscole 
I've created a folder in the sacro-ml prepository called experiments and pushed any notebook into there.

I suggest that we keep a division between the repo holding the main trolling (aisdc) and the repo holding experimental work where we are developing metrics and attacks such as the one @simonrnss suggests above. 
Does that make sense?
Can we transfer this issue to a different repo?

**Comment by jim-smith** [comment]
moved to sacro-ml repo
