### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by albacrespi** [AI-SDC/AI-SDC#253]
Are the dependencies on Tensorflow and Tensorflow-privacy really required or can they be optional? It's giving issues to install on the TRE.

**Comment by jim-smith** [comment]
@albacrespi it's a tricky one that Richard and I have debated a few times.
They are there at present because they a re needed by the SafeKerasClassifier class.

Richard is offline at the moment but  last thing I knew he had done lots of work making really complex setup.py / requirements.py installer script that had bene tested and worked with lots of different versions of python.
I assume that you are installing this into a clean new python venv, what version of python has that got in it?

**Comment by jim-smith** [comment]
@albacrespi @rpreen @simonrnss   
Longer term we need to look at this.   

There is a new version of tensor flow-privacy available with fewer dependencies on specific (old) versions of other libraries, but we have not had a chance to check that.

If it is no less complex than the current situation we may need to consider either:
1. Making a version without the SafeKerasClassifier class
2. splitting the repo in two so that  the attacks can be run without the safemodel wrappers.

**Comment by manics** [comment]
In HIC we use conda-forge for most Python dependencies so we're happy to install any available non-EOL version of Python. tensorflow-privacy isn't available on conda-forge.

For now we're using [conda-pack](https://conda.github.io/conda-pack/) to bring in packages that aren't available in conda-forge, which so far seems to work with pip installed packages too. I'm about to add it to our TRE so @albacrespi will soon be able to tell us whether it works!

You might already be aware.... but in case you're not you can have optonial python dependencies (`extras_require`) in your setup file instead of splitting the repo. You could then conditionally make methods available:
```python
try:
    import tensorflow_privacy
    tensorflow_privacy_available = True
except ImportError:
    tensorflow_privacy_available = False
```
